name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  COIN_NAME: app
  BUILD_DIR: app-build
  COMPRESS_DIR: raptoreum-compress
  TEST_LOG_ARTIFACT_DIR: test-logs

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install system dependencies
      run: brew install boost ninja
    - name: Install Android Dependencies
      run: |
        tools/install-android-dependencies
    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@v1.1.2
      with:
        path: build/local
        key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
      if: steps.internal_cache.outputs.cache-hit != 'true'
    - name: Run test
      run: |
        tools/generate-files
        tools/android-test
    - name: Build sample app
      run: |
        tools/samples-build android
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload window installation file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.COIN_NAME }}-win-installation-${{ env.BUILD_VERSION }}
          path: win64-installation
